### ISSUE TITLE
[Bug]: start new project

### ISSUE THREAD

**Issue by hooman-mirghasemi** [Pythagora-io/gpt-pilot#1002]
### Version

VisualStudio Code extension

### Operating System

Ubuntu Linux

### What happened?

when I click on start project 

Traceback (most recent call last):
  File "/home/hooman/Desktop/openPilot/gpt-pilot/main.py", line 29, in <module>
    sys.exit(run_pythagora())
  File "/home/hooman/Desktop/openPilot/gpt-pilot/core/cli/main.py", line 215, in run_pythagora
    success = run(async_main(ui, db, args))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/hooman/Desktop/openPilot/gpt-pilot/core/cli/main.py", line 204, in async_main
    success = await run_pythagora_session(sm, ui, args)
  File "/home/hooman/Desktop/openPilot/gpt-pilot/core/cli/main.py", line 141, in run_pythagora_session
    if not await llm_api_check(ui):
  File "/home/hooman/Desktop/openPilot/gpt-pilot/core/cli/main.py", line 87, in llm_api_check
    resp = await llm_client.api_check()
  File "/home/hooman/Desktop/openPilot/gpt-pilot/core/llm/base.py", line 307, in api_check
    resp, _log = await self(convo)
  File "/home/hooman/Desktop/openPilot/gpt-pilot/core/llm/base.py", line 245, in __call__
    err_code = err.response.json().get("error", {}).get("code", "")
  File "/home/hooman/Desktop/openPilot/gpt-pilot/venv/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by hooman-mirghasemi** [comment]
I should remove all comments in config.json file now it start working
