### ISSUE TITLE
Project won't resume after interrupt

### ISSUE THREAD

**Issue by gmelfe** [Pythagora-io/gpt-pilot#104]
When gpt-pilot execution gets interrupted (e.g. with CTRL+C), the project can not be resumed. 
When trying to resume the project with the app_id, I get prompted to describe the project again.
The project was already in the implementation stage (requirements were complete, architecture definition, etc.).

**Comment by benrman** [comment]
Yeah I'm having the same issue.

**Comment by nalbion** [comment]
@gmelfe @benrman does it work if you use `python main.py workspace=/src/my_project`?

**Comment by benrman** [comment]
I am pretty sure that's what I did.  I'll give it a shot when I get home later today.  Thanks

**Comment by gmelfe** [comment]
I've tried, it doesn't work. 
Similar effect as trying to resume with app_id.

**Comment by lrojas94** [comment]
I get all sorts of errors when doing this too. It errors out every time and on multiple projects. Seems like it's trying to re-run all steps again (?) as from what I can tell it even rolled back one of my sampels.

Here's a sample error:
```
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/mnt/d/Work/gpt-pilot/pilot/main.py", line 52, in <module>
    project.start()
  File "/mnt/d/Work/gpt-pilot/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/mnt/d/Work/gpt-pilot/pilot/helpers/agents/Developer.py", line 40, in start_coding
    self.implement_task(i, dev_task)
  File "/mnt/d/Work/gpt-pilot/pilot/helpers/agents/Developer.py", line 67, in implement_task
    return self.execute_task(convo_dev_task, task_steps, development_task=development_task, continue_development=True, is_root_task=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Work/gpt-pilot/pilot/helpers/agents/Developer.py", line 260, in execute_task
    result = self.step_human_intervention(convo, step)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Work/gpt-pilot/pilot/helpers/agents/Developer.py", line 136, in step_human_intervention
    return_value = self.debugger.debug(convo, user_input=response['user_input'], issue_description=step['human_intervention_description'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Work/gpt-pilot/pilot/helpers/Debugger.py", line 44, in debug
    debugging_plan = convo.send_message('dev_ops/debug.prompt',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Work/gpt-pilot/pilot/helpers/AgentConvo.py", line 89, in send_message
    response = parse_agent_response(response, function_calls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Work/gpt-pilot/pilot/utils/function_calling.py", line 73, in parse_agent_response
    values = list(json.loads(text).values())
                  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by nalbion** [comment]
@lrojas94 I've recently pushed some changes which should provide more robust handling of JSON responses from the LLM.

Can you please make sure you're running with the latest version from `main`? If you're still getting these errors from `function_calling.py` it would be helpful if you could share your logs from `logging/debug.log`

**Comment by nalbion** [comment]
@gmelfe hopefully this will be resolved by https://github.com/Pythagora-io/gpt-pilot/pull/149.  You may not be able to recover old projects, but new projects should be resumable.

**Comment by LeonOstrez** [comment]
should be fixed with https://github.com/Pythagora-io/gpt-pilot/pull/149
