### ISSUE TITLE
[Bug]: node_sqlite3.node is not a valid Win32 application

### ISSUE THREAD

**Issue by MoazAlkharfan** [Pythagora-io/gpt-pilot#1046]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

Pythagora fails to run when clicking the icon.

Extension host output:

```
2024-07-04 14:24:52.438 [info] ExtensionService#_doActivateExtension pythagoratechnologies.gpt-pilot-vs-code, startup: false, activationEvent: 'onStartupFinished'
2024-07-04 14:24:53.042 [error] Activating extension pythagoratechnologies.gpt-pilot-vs-code failed due to an error:
2024-07-04 14:24:53.042 [error] Error: \\?\#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\pythagoratechnologies.gpt-pilot-vs-code-0.2.11\node_modules\sqlite3\build\Release\node_sqlite3.node is not a valid Win32 application.
\\?\#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\pythagoratechnologies.gpt-pilot-vs-code-0.2.11\node_modules\sqlite3\build\Release\node_sqlite3.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.S._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6035)
    at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:31788)
    at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:139:34301)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at Module.require (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:8:42349)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
    at bindings (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\pythagoratechnologies.gpt-pilot-vs-code-0.2.11\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\pythagoratechnologies.gpt-pilot-vs-code-0.2.11\node_modules\sqlite3\lib\sqlite3-binding.js:1:99)
    at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.S._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6035)
    at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:31788)
    at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:139:34301)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at Module.require (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:8:42349)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
    at Object.<anonymous> (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\pythagoratechnologies.gpt-pilot-vs-code-0.2.11\node_modules\sqlite3\lib\sqlite3.js:2:17)
    at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.S._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6035)
    at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:31788)
    at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:139:34301)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at Module.require (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:8:42349)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
    at Object.<anonymous> (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\pythagoratechnologies.gpt-pilot-vs-code-0.2.11\out\providers\SidebarProvider.js:12:17)
    at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.S._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6035)
    at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:31788)
    at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:139:34301)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at Module.require (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:8:42349)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
    at Object.<anonymous> (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\pythagoratechnologies.gpt-pilot-vs-code-0.2.11\out\extension.js:5:27)
    at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.S._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6035)
    at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:31788)
    at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:139:34301)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at Module.require (#MANUALLY_HIDDEN_USER_PROFILE_DIRECTORY#\.vscode\extensions\github.copilot-chat-0.17.0\dist\extension.js:8:42349)
    at require (node:internal/modules/helpers:130:18)
    at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
    at m.xb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:32967)
    at async Promise.all (index 0)
```

**Comment by LeonOstrez** [comment]
We released new version that has a fix for that
