### ISSUE TITLE
AttributeError: module 'os' has no attribute 'setsid' on Windows 10

### ISSUE THREAD

**Issue by timuryung** [Pythagora-io/gpt-pilot#11]
When it's trying to run the command following error occurs:
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    project.start()
  File "C:\Users\Samsung1\Downloads\gpt-pilot-main\gpt-pilot-main\pilot\helpers\Project.py", line 81, in start
    self.developer.start_coding()
  File "C:\Users\Samsung1\Downloads\gpt-pilot-main\gpt-pilot-main\pilot\helpers\agents\Developer.py", line 32, in start_coding
    self.implement_task()
  File "C:\Users\Samsung1\Downloads\gpt-pilot-main\gpt-pilot-main\pilot\helpers\agents\Developer.py", line 53, in implement_task
    self.execute_task(convo_dev_task, task_steps, continue_development=True)
  File "C:\Users\Samsung1\Downloads\gpt-pilot-main\gpt-pilot-main\pilot\helpers\agents\Developer.py", line 71, in execute_task
    run_command_until_success(data['command'], data['timeout'], convo, additional_message=additional_message)
  File "C:\Users\Samsung1\Downloads\gpt-pilot-main\gpt-pilot-main\pilot\helpers\cli.py", line 188, in run_command_until_success
    cli_response = execute_command(convo.agent.project, command, timeout, force)
  File "C:\Users\Samsung1\Downloads\gpt-pilot-main\gpt-pilot-main\pilot\helpers\cli.py", line 73, in execute_command
    process = run_command(command, project.root_path, q, q_stderr, pid_container)
  File "C:\Users\Samsung1\Downloads\gpt-pilot-main\gpt-pilot-main\pilot\helpers\cli.py", line 32, in run_command
    preexec_fn=os.setsid,
AttributeError: module 'os' has no attribute 'setsid'

**Comment by jcobreros** [comment]
Same problem here

**Comment by zenchantlive** [comment]
same issue here. vs code on windows

**Comment by LeonOstrez** [comment]
we pushed commit that should fix this issue. Please let me know if it works for you now 🙏

**Comment by jcobreros** [comment]
That fixed it! Thanks!
