### ISSUE TITLE
[Bug]: RuntimeError: Event loop is closed!

### ISSUE THREAD

**Issue by milos8893** [Pythagora-io/gpt-pilot#1108]
### Version

Command-line (Python) version

### Operating System

Windows 10

### What happened?

When I start the existing project it asks for the next step and then just crashes.

```
(venv) PS M:\Dropbox\GPTPilot\gpt-pilot> python main.py --project 1f5d60aa-f674-4544-ac74-816e1250e9fc
[Developer] Starting new task with description:

Add the ability to delete projects, with a confirmation prompt to prevent accidental deletions.

[Developer] Do you want to execute the above task?
  [yes]: Yes (default)
  [edit]: Edit Task
  [skip]: Skip Task
> skip
[Developer] Skipping task...

[Pythagora] Stopping Pythagora due to error:

File `core/cli/main.py`, line 38, in run_project
    success = await orca.run()
File `core/agents/orchestrator.py`, line 85, in run
    response = await self.handle_done(agent, response)
File `core/agents/orchestrator.py`, line 185, in handle_done
    await self.state_manager.commit()
File `core/state/state_manager.py`, line 236, in commit
    await self.commit_with_retry()
RetryError: RetryError[<Future at 0x27e43451c40 state=finished raised PendingRollbackError>]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027E3E853280>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I tried, answering both skip and yes.
Tried reinstalling the venv

I am on step 80. How do I fix it?

**Comment by milos8893** [comment]
I have fixed it myself.
I think its an issue with Windows and sqlite.
pythagora.db is corrupted!
What you need to do is, export all the data from it and recreate the database with that data!
