### ISSUE TITLE
KeyError: '\\U'

### ISSUE THREAD

**Issue by heijligers** [Pythagora-io/gpt-pilot#134]
I just got this one.

---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/sre_parse.py", line 1051, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\U'

During handling of the above exception, another exception occurred:
`
Traceback (most recent call last):
  File "/Users/datascience/PycharmProjects/gpt-pilot2/pilot/main.py", line 90, in <module>
    project.start()
  File "/Users/datascience/PycharmProjects/gpt-pilot2/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/Users/datascience/PycharmProjects/gpt-pilot2/pilot/helpers/agents/Developer.py", line 40, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/datascience/PycharmProjects/gpt-pilot2/pilot/helpers/agents/Developer.py", line 67, in implement_task
    return self.execute_task(convo_dev_task, task_steps, development_task=development_task, continue_development=True, is_root_task=True)
  File "/Users/datascience/PycharmProjects/gpt-pilot2/pilot/helpers/agents/Developer.py", line 228, in execute_task
    convo.load_branch(function_uuid)
  File "/Users/datascience/PycharmProjects/gpt-pilot2/pilot/helpers/AgentConvo.py", line 152, in load_branch
    self.replace_files()
  File "/Users/datascience/PycharmProjects/gpt-pilot2/pilot/helpers/AgentConvo.py", line 159, in replace_files
    self.replace_file_content(msg['content'], file['path'], file['content'])
  File "/Users/datascience/PycharmProjects/gpt-pilot2/pilot/helpers/AgentConvo.py", line 168, in replace_file_content
    updated_message, num_replacements = re.subn(pattern, new_section_content, message, flags=re.DOTALL)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 220, in subn
    return _compile(pattern, flags).subn(repl, string, count)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/sre_parse.py", line 1054, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \U at position 1193 (line 33, column 25)
--------------------------------------------------`

**Comment by heijligers** [comment]
update... Weirdly enough when running the code inside the pycharm debugger, it hasn't appeared so far.

Can anyone explain what the --get-created-apps-with-steps option is supposed to do?

**Comment by nalbion** [comment]
Is this a suggested file name by the LLM? Can you provide logs from `pilot/logger/debug.log`?
