### ISSUE TITLE
Exception: OpenAI API error happened

### ISSUE THREAD

**Issue by Darwinium** [Pythagora-io/gpt-pilot#136]
Got the latest version from github and got the same error as here #35 

And whenever I try to restart it
python main.py app_id=9e6dec56-1ca4-486b-944d-5cc6828eb513

I got the same output.

**Here's the output from Terminal:**

```
--------- EXECUTE COMMAND ----------
If yes, just press ENTER
Restoring user input id 1: yes
Restoring command run response id 1:
```
stderr:
```
/bin/sh: npm: command not found

```
stdout:
```

``````
Restoring development step with id 3

Dev step 3

NEEDS_DEBUGGING

Got incorrect CLI response:
stderr:
```
/bin/sh: npm: command not found

```
stdout:
```

```
-------------------
Restoring development step with id 4

Dev step 4

#0
type: command
command: {'command': 'which npm', 'timeout': 2000}
check_if_fixed: False
#1
type: command
command: {'command': 'which node', 'timeout': 2000}
check_if_fixed: False
#2
type: command
command: {'command': 'node --version', 'timeout': 2000}
check_if_fixed: False
#3
type: command
command: {'command': 'npm --version', 'timeout': 2000}
check_if_fixed: False
#4
type: command
command: {'command': 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash', 'timeout': 60000}
check_if_fixed: False
#5
type: command
command: {'command': 'nvm install node', 'timeout': 60000}
check_if_fixed: False
#6
type: command
command: {'command': 'npm init -y', 'timeout': 5000}
check_if_fixed: True

--------- EXECUTE COMMAND ----------
If yes, just press ENTER
Restoring user input id 2: 
Restoring command run response id 2:
```
stdout:
```

``````
Restoring development step with id 5

Dev step 5

NEEDS_DEBUGGING

Got incorrect CLI response:
stdout:
```

```
-------------------
Restoring development step with id 6
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/brainfree/projects/gpt-pilot/pilot/main.py", line 90, in <module>
    project.start()
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/agents/Developer.py", line 40, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/agents/Developer.py", line 67, in implement_task
    return self.execute_task(convo_dev_task, task_steps, development_task=development_task, continue_development=True, is_root_task=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/agents/Developer.py", line 231, in execute_task
    result = self.step_command_run(convo, step, i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/agents/Developer.py", line 97, in step_command_run
    return run_command_until_success(data['command'], data['timeout'], convo, additional_message=additional_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/cli.py", line 310, in run_command_until_success
    return convo.agent.debugger.debug(convo, {'command': command, 'timeout': timeout})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/Debugger.py", line 55, in debug
    response = self.agent.project.developer.execute_task(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/agents/Developer.py", line 231, in execute_task
    result = self.step_command_run(convo, step, i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/agents/Developer.py", line 97, in step_command_run
    return run_command_until_success(data['command'], data['timeout'], convo, additional_message=additional_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/cli.py", line 310, in run_command_until_success
    return convo.agent.debugger.debug(convo, {'command': command, 'timeout': timeout})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/Debugger.py", line 44, in debug
    debugging_plan = convo.send_message('dev_ops/debug.prompt',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brainfree/projects/gpt-pilot/pilot/helpers/AgentConvo.py", line 84, in send_message
    raise Exception("OpenAI API error happened.")
Exception: OpenAI API error happened.
--------------------------------------------------

**Comment by nalbion** [comment]
@Darwinium can you please provide the logs from `/Users/brainfree/projects/gpt-pilot/pilot/logger/debug.log`

**Comment by nalbion** [comment]
I've added error handling and logging in PR #133 which should help resolve or clarify this issue

**Comment by Darwinium** [comment]
@nalbion unfortunately I started the new project, and as I can see, it saves in the logfile only the output from the last project (maybe it's a bug). That's why, in this file, I have data related to the last run only
