### ISSUE TITLE
"There was a problem with request to openai API: LLM did not respond with JSON"

### ISSUE THREAD

**Issue by Timeroot** [Pythagora-io/gpt-pilot#210]
I tried three times, with similar descriptions of a simple one-page website to navigate some data, and each time it got stuck fairly early. The three runs varied in what it did, in significant ways (trying different packages / developments / usage of git), but it always ended with:
```
#0
type: commandThere was a problem with request to openai API:
LLM did not respond with JSON
? Do you want to try make the same request again? If yes, just press ENTER. Otherwise, type 'no'. 
```
Hitting ENTER repeatedly made it keep giving the same error. If I typed 'no', the process would exit, and then if I restarted it, it would just complain about something similar -- for instance
```
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/home/timeroot/ml/gpt-pilot/pilot/main.py", line 53, in <module>
    project.start()
  File "/home/timeroot/ml/gpt-pilot/pilot/helpers/Project.py", line 141, in start
    self.developer.start_coding()
  File "/home/timeroot/ml/gpt-pilot/pilot/helpers/agents/Developer.py", line 41, in start_coding
    self.implement_task(i, dev_task)
  File "/home/timeroot/ml/gpt-pilot/pilot/helpers/agents/Developer.py", line 70, in implement_task
    return self.execute_task(convo_dev_task, task_steps, development_task=development_task, continue_development=True, is_root_task=True)
  File "/home/timeroot/ml/gpt-pilot/pilot/helpers/agents/Developer.py", line 272, in execute_task
    result = self.step_human_intervention(convo, step)
  File "/home/timeroot/ml/gpt-pilot/pilot/helpers/agents/Developer.py", line 146, in step_human_intervention
    return_value = self.debugger.debug(convo, user_input=response['user_input'], issue_description=step['human_intervention_description'])
  File "/home/timeroot/ml/gpt-pilot/pilot/helpers/Debugger.py", line 44, in debug
    debugging_plan = convo.send_message('dev_ops/debug.prompt',
  File "/home/timeroot/ml/gpt-pilot/pilot/helpers/AgentConvo.py", line 91, in send_message
    response = parse_agent_response(response, function_calls)
  File "/home/timeroot/ml/gpt-pilot/pilot/utils/function_calling.py", line 73, in parse_agent_response
    values = list(json.loads(text).values())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
--------------------------------------------------
```

What does this error indicate, and how can I repair it?

**Comment by nalbion** [comment]
If something goes wrong, and the response is `{}` we should not be saving it to the db

https://github.com/Pythagora-io/gpt-pilot/blob/624009b0b4eb2c8e8ed485d4f944628d0c421201/pilot/helpers/AgentConvo.py#L82
