### ISSUE TITLE
Resuming a project caused error and deleted all code files!

### ISSUE THREAD

**Issue by william2313** [Pythagora-io/gpt-pilot#220]
I had to abort GPT-Pilot as it got stuck at "command_test" (after 59 steps). 

I then tried to continue development with "python main.py app_id=.........".
It then picked up at "Now for the actual development" and started restoring development steps, starting with step 1.

When it got to restoring development step 6, GPT Pilot exited with an error (see below). The worst part is that it had now deleted all the code files (except main.py) that it had already created and that were in the project folder (under workspace). 

So I have now lost all the code it had already created in 59 steps!

Last part of output:

Restoring development step with id 6
Updated file /home/adam/gpt-pilot/workspace/Pac-Man/main.py
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/home/adam/gpt-pilot/pilot/main.py", line 53, in <module>
    project.start()
  File "/home/adam/gpt-pilot/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/home/adam/gpt-pilot/pilot/helpers/agents/Developer.py", line 41, in start_coding
    self.implement_task(i, dev_task)
  File "/home/adam/gpt-pilot/pilot/helpers/agents/Developer.py", line 68, in implement_task
    return self.execute_task(convo_dev_task, task_steps, development_task=development_task, continue_development=True, is_root_task=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/gpt-pilot/pilot/helpers/agents/Developer.py", line 298, in execute_task
    return self.task_postprocessing(convo, development_task, continue_development, result, function_uuid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/gpt-pilot/pilot/helpers/agents/Developer.py", line 185, in task_postprocessing
    return self.continue_development(convo, last_branch_name, continue_description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/gpt-pilot/pilot/helpers/agents/Developer.py", line 348, in continue_development
    task_steps = iteration_convo.send_message('development/parse_task.prompt', {
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/gpt-pilot/pilot/helpers/AgentConvo.py", line 91, in send_message
    response = parse_agent_response(response, function_calls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/gpt-pilot/pilot/utils/function_calling.py", line 73, in parse_agent_response
    values = list(json.loads(text).values())
                  ^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nalbion** [comment]
I suspect this will be fixed by https://github.com/Pythagora-io/gpt-pilot/pull/211.

The fix will only apply to apps which are created _using_ this change. You may be able to restore your project by deleting the corrupt record from your DB.

**Comment by william2313** [comment]
Hmm... yeah I got it working again. Thanks.

**Comment by kettmahhaa** [comment]
i have also problem when resuming project it delete my files
