### ISSUE TITLE
Unterminated string starting at: line 75 column 20 (char 11355)

### ISSUE THREAD

**Issue by zerofill** [Pythagora-io/gpt-pilot#23]
Basically everytime when gpt-pilot starts to generate code, it will run into Unterminated string error.

Often this is after it has been building some of the files.

If you rerun the prompt you run into the same issue.

It has done this on gpt-4 and gpt-3.5 16k on multiple different project attempts.

**Comment by zerofill** [comment]
Also if I try to restore development:

Restoring development step with id 4
Traceback (most recent call last):
  File "/home/zero/repos/gpt-pilot/pilot/main.py", line 35, in <module>
    project.start()
  File "/home/zero/repos/gpt-pilot/pilot/helpers/Project.py", line 81, in start
    self.developer.start_coding()
  File "/home/zerol/repos/gpt-pilot/pilot/helpers/agents/Developer.py", line 32, in start_coding
    self.implement_task()
  File "/home/zerol/repos/gpt-pilot/pilot/helpers/agents/Developer.py", line 51, in implement_task
    task_steps = convo_dev_task.send_message('development/parse_task.prompt', {}, IMPLEMENT_TASK)
  File "/home/zero/repos/gpt-pilot/pilot/helpers/AgentConvo.py", line 59, in send_message
    raise Exception("OpenAI API error happened.")
Exception: OpenAI API error happened.

**Comment by zvone187** [comment]
`Unterminated string error.` is, unfortunately, when OpenAI returns an incorrect JSON format during the function call. I'll need to add postprocessing to the function calling since it really doesn't work too well.

Re: restoring development - can you try resuming the development from one development step before?
