### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by mijhaels** [Pythagora-io/gpt-pilot#275]
![image](https://github.com/Pythagora-io/gpt-pilot/assets/67170467/14b34a75-e8fc-4eab-b895-fedd902389c8)

**Comment by Scratch-project** [comment]
go to `"/home/mijhaels/Documentos/git/gpt-pilot/pilot/helpers/Project.py",` and set the line 216 to 

`file_content = open(full_path, 'r', encoding='iso-8859-1').read()`

**Comment by Umpire2018** [comment]
> go to `"/home/mijhaels/Documentos/git/gpt-pilot/pilot/helpers/Project.py",` and set the line 216 to
> 
> `file_content = open(full_path, 'r', encoding='iso-8859-1').read()`

@Scratch-project I have added `utf-8` encoding in #257 , i think that's enough for most scenario, maybe need to add error handle for this.

**Comment by pezzos** [comment]
I have almost the same issue:
```---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/main.py", line 67, in <module>
    project.start()
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 50, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 84, in implement_task
    "files": self.project.get_all_coded_files(),
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Project.py", line 192, in get_all_coded_files
    files = self.get_files([file.path + '/' + file.name for file in files])
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Project.py", line 216, in get_files
    file_content = open(full_path, 'r').read()
  File "/Users/a.pezzotta/devtools/pyenv/versions/3.10.2/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 10: invalid continuation byte
--------------------------------------------------
```

I tried to do what @Scratch-project said but same:
```---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/main.py", line 67, in <module>
    project.start()
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 50, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 96, in implement_task
    result = self.execute_task(convo_dev_task,
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 343, in execute_task
    result = self.step_human_intervention(convo, step)
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 207, in step_human_intervention
    response['success'] = self.debugger.debug(convo,
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Debugger.py", line 46, in debug
    llm_response = convo.send_message('dev_ops/debug.prompt',
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/AgentConvo.py", line 101, in send_message
    response = parse_agent_response(response, function_calls)
  File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/utils/function_calling.py", line 73, in parse_agent_response
    return json.loads(text)
  File "/Users/a.pezzotta/devtools/pyenv/versions/3.10.2/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/a.pezzotta/devtools/pyenv/versions/3.10.2/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/a.pezzotta/devtools/pyenv/versions/3.10.2/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
--------------------------------------------------```

Any idea?

**Comment by bigvo** [comment]
> I have almost the same issue:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/main.py", line 67, in <module>
>     project.start()
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Project.py", line 134, in start
>     self.developer.start_coding()
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 50, in start_coding
>     self.implement_task(i, dev_task)
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 84, in implement_task
>     "files": self.project.get_all_coded_files(),
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Project.py", line 192, in get_all_coded_files
>     files = self.get_files([file.path + '/' + file.name for file in files])
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Project.py", line 216, in get_files
>     file_content = open(full_path, 'r').read()
>   File "/Users/a.pezzotta/devtools/pyenv/versions/3.10.2/lib/python3.10/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 10: invalid continuation byte
> --------------------------------------------------
> ```
> 
> I tried to do what @Scratch-project said but same:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/main.py", line 67, in <module>
>     project.start()
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Project.py", line 134, in start
>     self.developer.start_coding()
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 50, in start_coding
>     self.implement_task(i, dev_task)
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 96, in implement_task
>     result = self.execute_task(convo_dev_task,
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 343, in execute_task
>     result = self.step_human_intervention(convo, step)
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/agents/Developer.py", line 207, in step_human_intervention
>     response['success'] = self.debugger.debug(convo,
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/Debugger.py", line 46, in debug
>     llm_response = convo.send_message('dev_ops/debug.prompt',
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/helpers/AgentConvo.py", line 101, in send_message
>     response = parse_agent_response(response, function_calls)
>   File "/Users/a.pezzotta/Dev/gpt-pilot/pilot/utils/function_calling.py", line 73, in parse_agent_response
>     return json.loads(text)
>   File "/Users/a.pezzotta/devtools/pyenv/versions/3.10.2/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/Users/a.pezzotta/devtools/pyenv/versions/3.10.2/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/Users/a.pezzotta/devtools/pyenv/versions/3.10.2/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> --------------------------------------------------```
> 
> Any idea?
> ```

Problem is in file tracker, which tries to restore corrupted file from db, probably created by compiler, inspect files in your project and set IGNORE_FOLDERS variable for GPT Pilot

**Comment by AlchemR** [comment]
I started with an initial error, and followed what @Scratch-project suggested, and then it gave an error near identical to @pezzos found.

It started because it was asking for user-intervention where I was creating an icon file in the directory, and it timed out.  
It looks like 
`---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/main.py", line 67, in <module>
    project.start()
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/helpers/agents/Developer.py", line 50, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/helpers/agents/Developer.py", line 96, in implement_task
    result = self.execute_task(convo_dev_task,
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/helpers/agents/Developer.py", line 335, in execute_task
    result = self.step_command_run(convo, step, i, success_with_cli_response=need_to_see_output)
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/helpers/agents/Developer.py", line 155, in step_command_run
    return run_command_until_success(convo, data['command'],
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/helpers/cli.py", line 480, in run_command_until_success
    success = convo.agent.debugger.debug(convo, {
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/helpers/Debugger.py", line 46, in debug
    llm_response = convo.send_message('dev_ops/debug.prompt',
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/helpers/AgentConvo.py", line 101, in send_message
    response = parse_agent_response(response, function_calls)
  File "/Users/peter/Desktop/ChromeEXT/gpt-pilot/pilot/utils/function_calling.py", line 73, in parse_agent_response
    return json.loads(text)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Is there a way to roll back the DB to that step?
I've tried to run the steps prior to it and it seems like it's trying to parse an agent response that is "None".
Is the response "none" because the DB is corrupted?

I checked my .env files and while it was pointing to a folder that didnt exist, I commented the additional out that line so it wouldn't look for an "ignore folder" but it did not fix the issue.

What more am I missing?

**Comment by sarahedwin442** [comment]
I want to use this golden medium to Appreciate Dr Kuda for making my dream come through. I was on the internet when I saw people posting and talking about Dr Kuda. On How he has help them in winning huge amounts in lottery ticket, My name is Sarah Edwin, this is my story on how I win $754.6 Million Dollars, After reading the article talking good about Dr Kuda I contacted Dr Kuda I told him to help me win the Powerball lottery, Then he respond to me by saying he will help me after working with Dr Kuda, and assured me that I will win the Powerball Lottery Draw, Which I believe. After working with Dr Kuda, he gave me a five digit number and ask me to go and play it which I did today, now i’m here shearing a testimony about this same man Dr Kuda Changed my life by helping me to win $754.6 Million Dollars all thanks to you Dr Kuda, I will keep talking about your good work, because you are a man of your word I hope people that really need this help will come across it for you to help them as well. If you want to win biggest in lottery contact Dr. Kuda today and be rest assured of winning lottery game, contact via email: drkudaspelltemple@gmail.com Or Call and Whatsapp Number +1 (346) 478-1991

**Comment by pezzos** [comment]
@LeonOstrez, @nalbion: could you help us with that please? 😄

**Comment by pezzos** [comment]
Oh, great! Thank you so much 😉

**Comment by glwdl** [comment]
> go to `"/home/mijhaels/Documentos/git/gpt-pilot/pilot/helpers/Project.py",` and set the line 216 to
> 
> `file_content = open(full_path, 'r', encoding='iso-8859-1').read()`

Solved my problem
