### ISSUE TITLE
gpt-pilot fails to resume an existing project

### ISSUE THREAD

**Issue by simjega** [Pythagora-io/gpt-pilot#280]
Also running into a json parsing issue similar to https://github.com/Pythagora-io/gpt-pilot/issues/104 / https://github.com/Pythagora-io/gpt-pilot/issues/210

Stacktrace: 
```
Restoring development step with id 17
Updated file /Users/jay/code/gpt-pilot/workspace/Todo_App/package.json
Updated file /Users/jay/code/gpt-pilot/workspace/Todo_App/.env
Updated file /Users/jay/code/gpt-pilot/workspace/Todo_App/server.js
Updated file /Users/jay/code/gpt-pilot/workspace/Todo_App/models/Todo.js
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/jay/code/gpt-pilot/pilot/main.py", line 67, in <module>
    project.start()
  File "/Users/jay/code/gpt-pilot/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/Users/jay/code/gpt-pilot/pilot/helpers/agents/Developer.py", line 50, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/jay/code/gpt-pilot/pilot/helpers/agents/Developer.py", line 88, in implement_task
    response = convo_dev_task.send_message('development/parse_task.prompt', {
  File "/Users/jay/code/gpt-pilot/pilot/helpers/AgentConvo.py", line 106, in send_message
    response = parse_agent_response(response, function_calls)
  File "/Users/jay/code/gpt-pilot/pilot/utils/function_calling.py", line 73, in parse_agent_response
    return json.loads(text)
  File "/Users/jay/.pyenv/versions/3.9.5/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/jay/.pyenv/versions/3.9.5/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jay/.pyenv/versions/3.9.5/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Full trace: https://pastebin.pl/view/bfb656ab

I ran a debugger to see what is going on and it looks like we're trying to parse a non-json output in `parse_agent_response`
for a dev step that has `function_calls`.  
AgentConvo.send_message
<img width="914" alt="image" src="https://github.com/Pythagora-io/gpt-pilot/assets/959696/69cbd1d7-6709-4236-baa1-72f06884b601">

<img width="1132" alt="image" src="https://github.com/Pythagora-io/gpt-pilot/assets/959696/605c3a7d-805c-4e82-9d44-3cd0d757c990">

**Comment by AlchemR** [comment]
I think there's some crossover in the same issue in [275](https://github.com/Pythagora-io/gpt-pilot/issues/275)

It happened for me as I was editing an icon file, and my cli timed-out.

**Comment by LeonOstrez** [comment]
We are aware of the issue and are currently working on this.
as @AlchemR mentioned, please see https://github.com/Pythagora-io/gpt-pilot/issues/275 for future updates.

marking as duplicate and closing
