### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by lerisse** [Pythagora-io/gpt-pilot#337]
This error is occuring all the time during my build. I'm unable to figure out why and when this happens. I have tried advanced mode as well as regular. Currently using GTP-4.

---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/main.py", line 77, in <module>
    project.start()
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/helpers/Project.py", line 141, in start
    self.developer.start_coding()
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/helpers/agents/Developer.py", line 54, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/helpers/agents/Developer.py", line 101, in implement_task
    result = self.execute_task(convo_dev_task,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/helpers/agents/Developer.py", line 380, in execute_task
    convo.load_branch(function_uuid)
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/helpers/AgentConvo.py", line 183, in load_branch
    self.replace_files()
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/helpers/AgentConvo.py", line 190, in replace_files
    self.replace_file_content(msg['content'], file['path'], file['content'])
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/helpers/AgentConvo.py", line 219, in replace_file_content
    new_content_escaped = self.escape_specials(new_content)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/-/Projects/JukeBox App/gpt-pilot/pilot/helpers/AgentConvo.py", line 193, in escape_specials
    s = s.replace("\\", "\\\\")
        ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'

**Comment by senko** [comment]
Thanks for reporting this.

Did the project (where this crashed) have any files that weren't text files (such as images, zip files, etc...)?
