### ISSUE TITLE
stops at Dev stop 4 it escapes

### ISSUE THREAD

**Issue by kingshah13** [Pythagora-io/gpt-pilot#341]
I don't what happens but at Dev stop 4 it escapes with a lot of errors. I am not a programmer or a coder just your average Joe who knows how to follow instructions and suffers from "automate my every task so I can sleep at the job" syndrome. 

Traceback (most recent call last):
  File "C:\Users\User\gpt-pilot\pilot\main.py", line 77, in <module>
    project.start()
  File "C:\Users\User\gpt-pilot\pilot\helpers\Project.py", line 141, in start
    self.developer.start_coding()
  File "C:\Users\User\gpt-pilot\pilot\helpers\agents\Developer.py", line 54, in start_coding
    self.implement_task(i, dev_task)
  File "C:\Users\User\gpt-pilot\pilot\helpers\agents\Developer.py", line 101, in implement_task
    result = self.execute_task(convo_dev_task,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\gpt-pilot\pilot\helpers\agents\Developer.py", line 380, in execute_task
    convo.load_branch(function_uuid)
  File "C:\Users\User\gpt-pilot\pilot\helpers\AgentConvo.py", line 183, in load_branch
    self.replace_files()
  File "C:\Users\User\gpt-pilot\pilot\helpers\AgentConvo.py", line 190, in replace_files
    self.replace_file_content(msg['content'], file['path'], file['content'])
  File "C:\Users\User\gpt-pilot\pilot\helpers\AgentConvo.py", line 223, in replace_file_content
    updated_message, num_replacements = re.subn(pattern, new_section_content, message, flags=re.DOTALL)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 196, in subn
    return _compile(pattern, flags).subn(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 317, in _subx
    template = _compile_repl(template, pattern)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 308, in _compile_repl
    return _parser.parse_template(repl, pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 1080, in parse_template
    raise s.error('bad escape %s' % this, len(this)) from None
re.error: bad escape \m at position 28 (line 1, column 29)

**Comment by senko** [comment]
Hey, thanks for reporting this!

We just pushed a fix for this in `main` yesterday (PR https://github.com/Pythagora-io/gpt-pilot/pull/355), if you get the newest version of GPT Pilot this should be fixed.

Please try it out and let us know here in the comments whether you get any more of these errors.

**Comment by kingshah13** [comment]
Thanks for the update I'll update as soon as I get time to work on it. 😀

**Comment by kingshah13** [comment]
it safe to we can close this.
