### ISSUE TITLE
Exception: OpenAI API error happened.

### ISSUE THREAD

**Issue by gmelfe** [Pythagora-io/gpt-pilot#35]
Context: 
- gpt-pilot fails to execute a command requiring super-user grants.
- user executes the command manually
- The user says "no" when asked if the command should be run again.
- App development gets stuck in the following error: 

Traceback (most recent call last):
  File ".../gpt-pilot/pilot/main.py", line 35, in <module>
    project.start()
  File ".../gpt-pilot/pilot/helpers/Project.py", line 81, in start
    self.developer.start_coding()
  File ".../gpt-pilot/pilot/helpers/agents/Developer.py", line 32, in start_coding
    self.implement_task()
  File ".../gpt-pilot/pilot/helpers/agents/Developer.py", line 53, in implement_task
    self.execute_task(convo_dev_task, task_steps, continue_development=True)
  File ".../gpt-pilot/pilot/helpers/agents/Developer.py", line 71, in execute_task
    run_command_until_success(data['command'], data['timeout'], convo, additional_message=additional_message)
  File ".../gpt-pilot/pilot/helpers/cli.py", line 222, in run_command_until_success
    debug(convo, {'command': command, 'timeout': timeout})
  File ".../gpt-pilot/pilot/helpers/cli.py", line 242, in debug
    success = convo.agent.project.developer.execute_task(
  File ".../gpt-pilot/pilot/helpers/agents/Developer.py", line 71, in execute_task
    run_command_until_success(data['command'], data['timeout'], convo, additional_message=additional_message)
  File ".../gpt-pilot/pilot/helpers/cli.py", line 222, in run_command_until_success
    debug(convo, {'command': command, 'timeout': timeout})
  File ".../gpt-pilot/pilot/helpers/cli.py", line 237, in debug
    debugging_plan = convo.send_message('dev_ops/debug.prompt',
  File ".../gpt-pilot/pilot/helpers/AgentConvo.py", line 59, in send_message
    raise Exception("OpenAI API error happened.")
Exception: OpenAI API error happened.

Trying to resume gpt-pilot project leads to the same error and quitting.

**Comment by LeonOstrez** [comment]
Thanks for trying out GPT-Pilot and opening the issue!

I added this bug to the list and I'll keep you updated here once we solve it.

**Comment by nalbion** [comment]
@gmelfe can you pull the latest version from `main` and try again?

**Comment by gmelfe** [comment]
Unfortunately I can't try again, that project is gone 😢

**Comment by nalbion** [comment]
"Gone"? 

Records of your prompts and LLM responses etc should be saved to the DB, but there are plans to make this more visibile.

We've recently improved logging and plan to make it easier to view, edit & import prompts etc

https://github.com/Pythagora-io/gpt-pilot/issues/121

**Comment by gmelfe** [comment]
Gone = wiped clean :-) 
I'll keep bug revealing projects alive for reference next time.
