### ISSUE TITLE
Project save_file fails when target file has no extension

### ISSUE THREAD

**Issue by gmelfe** [Pythagora-io/gpt-pilot#36]
When gpt-pilot tries to save a file without extension (e.g. Dockerfile), the following error occurs: 

Traceback (most recent call last):
  File ".../gpt-pilot/pilot/main.py", line 35, in <module>
    project.start()
  File ".../gpt-pilot/pilot/helpers/Project.py", line 81, in start
    self.developer.start_coding()
  File ".../gpt-pilot/pilot/helpers/agents/Developer.py", line 32, in start_coding
    self.implement_task()
  File ".../gpt-pilot/pilot/helpers/agents/Developer.py", line 53, in implement_task
    self.execute_task(convo_dev_task, task_steps, continue_development=True)
  File ".../gpt-pilot/pilot/helpers/agents/Developer.py", line 87, in execute_task
    self.project.save_file(data)
  File ".../gpt-pilot/pilot/helpers/Project.py", line 119, in save_file
    data['name'] = data['path'].rsplit('/', 1)[1]
IndexError: list index out of range

This should be an easy fix, depending on why the second condition was added to the if statement in the line above 👽

**Comment by LeonOstrez** [comment]
Thanks for opening the issue!

I added this bug to the list and I'll keep you updated here once we solve it.

**Comment by nalbion** [comment]
This should be resolved soon - https://github.com/Pythagora-io/gpt-pilot/pull/112
