### ISSUE TITLE
Issue on docker version where restarting from existing workspace brings weird errors

### ISSUE THREAD

**Issue by Atrone** [Pythagora-io/gpt-pilot#371]
For example sometimes I get:

```---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/usr/src/app/pilot/main.py", line 77, in <module>
    project.start()
  File "/usr/src/app/pilot/helpers/Project.py", line 141, in start
    self.developer.start_coding()
  File "/usr/src/app/pilot/helpers/agents/Developer.py", line 65, in start_coding
    self.implement_task(i, dev_task)
  File "/usr/src/app/pilot/helpers/agents/Developer.py", line 98, in implement_task
    "files": self.project.get_all_coded_files(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/Project.py", line 199, in get_all_coded_files
    files = self.get_files([file.path + '/' + file.name for file in files])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/Project.py", line 222, in get_files
    file_data = get_file_contents(full_path, self.root_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/files.py", line 55, in get_file_contents
    file_content = open(path, "r", encoding="utf-8").read()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/usr/src/app/workspace/Stripe_Heroku_Coupon_Reporter/Procfile/'
--------------------------------------------------
```

While sometimes I get IsADirectory error, and when I fix both errors manually (turning the Procfile to and from a directory), I then get llm['plan'] Key not found error.

I can't even paste the error messages because they are hard to recreate, but working on long running projects with this is has a lot of issues.

**Comment by techjeylabs** [comment]
closed after inacitivy
