### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by BytePhoenixCoding** [Pythagora-io/gpt-pilot#401]
Traceback (most recent call last):

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/main.py", line 77, in

project.start()

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/helpers/Project.py", line 90, in start

self.project_manager.get_project_description()

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/helpers/agents/ProductOwner.py", line 47, in get_project_description

self.project.args['name'] = clean_filename(ask_user(self.project, question))

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/prompts/prompts.py", line 58, in ask_user

answer = styled_text(project, question, hint=hint)

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/utils/questionary.py", line 37, in styled_text

response = print(question, type='user_input_request')

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/utils/custom_print.py", line 24, in print_to_external_process

return ipc_client_instance.listen()

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/helpers/ipc.py", line 32, in listen

message = json.loads(data)

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads

return _default_decoder.decode(s)

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/main.py", line 82, in

traceback.print_exc()

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/traceback.py", line 179, in print_exc

print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/traceback.py", line 121, in print_exception

print(line, file=file, end="")

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/utils/custom_print.py", line 19, in print_to_external_process

ipc_client_instance.send({

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/helpers/ipc.py", line 41, in send

self.client.sendall(data_length.to_bytes(4, byteorder='big'))

BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/main.py", line 88, in

exit_gpt_pilot(project, ask_feedback)

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/utils/exit.py", line 104, in exit_gpt_pilot

ask_user_email(project, path_id, ask_feedback)

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/utils/exit.py", line 90, in ask_user_email

feedback = styled_text(project, question, ignore_user_input_count=True)

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/utils/questionary.py", line 37, in styled_text

response = print(question, type='user_input_request')

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/utils/custom_print.py", line 19, in print_to_external_process

ipc_client_instance.send({

File "/Users/administrator/Documents/GPTPilot2/gpt-pilot/workspace/gpt-pilot/workspace/gpt-pilot/pilot/helpers/ipc.py", line 41, in send

self.client.sendall(data_length.to_bytes(4, byteorder='big'))

BrokenPipeError: [Errno 32] Broken pipe

What is the project name?

**Comment by senko** [comment]
BrokenPipeError in that place means the communication between the VSCode extension and gpt-pilot core (cli) has been interrupted - most likely the extension tab was closed. In theory, it should be a harmless error.

But in this case you shouldn't be able to see this (that error would go "nowhere"), so there's something else happening.

Can you please describe the situation (what you do, what happens, how often you can reproduce this)?

**Comment by senko** [comment]
Possible duplicate of #393 

@BytePhoenixCoding does the error also happen to you when you want to go back to the app selection screen?

**Comment by techjeylabs** [comment]
does this issue persist ?
