### ISSUE TITLE
[Bug]: Non functional. Crashes out on Create New App 

### ISSUE THREAD

**Issue by El7ias** [Pythagora-io/gpt-pilot#447]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

I'm very excited for this extension. However, it's not functional.  GPT-Pilot crashes out when selecting the New App button and after the "Waiting" box displays some block of code that I cannot read to troubleshoot as the extension then crashes out after 1 second of time passes. I'm Using VS Code w/ Python 10 installed and a new Open AI API key. Hope the problems are resolved soon, this extension is extremely promising and I can't wait to use a functioning version. All the best!

**Comment by ThomasEwing04** [comment]
crashing for me too

**Comment by senko** [comment]
Hi @El7ias @ThomasEwing04 we've made a bunch of fixes in the past few weeks, so if you want to try it for a spin again please let me know if/how it works for you! Feel free to reach out either here or in our Discord community.

**Comment by mmschoe** [comment]
Mine also crashes with the following error when I press Create New App...
`Traceback (most recent call last):
  File "c:\Users\matth\OneDrive\Documents\gpt-pilot\pilot\main.py", line 18, in <module>
    from helpers.Project import Project
  File "c:\Users\matth\OneDrive\Documents\gpt-pilot\pilot\helpers\Project.py", line 15, in <module>
    from prompts.prompts import ask_user
  File "c:\Users\matth\OneDrive\Documents\gpt-pilot\pilot\prompts\prompts.py", line 5, in <module>
    from utils.llm_connection import create_gpt_chat_completion
  File "c:\Users\matth\OneDrive\Documents\gpt-pilot\pilot\utils\llm_connection.py", line 18, in <module>
    from utils.function_calling import add_function_calls_to_request, FunctionCallSet, FunctionType
  File "c:\Users\matth\OneDrive\Documents\gpt-pilot\pilot\utils\function_calling.py", line 9, in <module>
    class FunctionParameters(TypedDict):
  File "c:\Users\matth\OneDrive\Documents\gpt-pilot\pilot\utils\function_calling.py", line 13, in FunctionParameters
    properties: dict[str, JsonType]
TypeError: 'type' object is not subscriptable`

Have tried uninstalling and reinstalling. It worked momentarily after initial install, but then I had issues with other pre-requisites like NodeJS runtime and MongoDB. After installing those, came back to try Pythagora again and started getting the above.
