### ISSUE TITLE
[Bug]: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Praj-17** [Pythagora-io/gpt-pilot#464]
### Version

Command-line (Python) version

### Operating System

Windows 11

### What happened?

I got this error after running python main.py in python version 3.8.0

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from helpers.Project import Project
  File "E:\CODING PLAYGROUND\CODE\gpt-pilot\pilot\helpers\Project.py", line 12, in <module>
    from prompts.prompts import ask_user
  File "E:\CODING PLAYGROUND\CODE\gpt-pilot\pilot\prompts\prompts.py", line 5, in <module>
    from utils.llm_connection import create_gpt_chat_completion
  File "E:\CODING PLAYGROUND\CODE\gpt-pilot\pilot\utils\llm_connection.py", line 18, in <module>
    from utils.function_calling import add_function_calls_to_request, FunctionCallSet, FunctionType
  File "E:\CODING PLAYGROUND\CODE\gpt-pilot\pilot\utils\function_calling.py", line 9, in <module>
    class FunctionParameters(TypedDict):
  File "E:\CODING PLAYGROUND\CODE\gpt-pilot\pilot\utils\function_calling.py", line 13, in FunctionParameters
    properties: dict[str, JsonType]
TypeError: 'type' object is not subscriptable

How do i fix it, I followed the exact same procedure referred in the Readme.

**Comment by senko** [comment]
This is due to the python version being too low, 3.8 is not supported.

Please try with Python 3.9 or higher.
