### ISSUE TITLE
[Bug]: ValueError: badly formed hexadecimal UUID string - peewee 

### ISSUE THREAD

**Issue by miketrimmel** [Pythagora-io/gpt-pilot#483]
### Version

Command-line (Python) version

### Operating System

MacOS

### What happened?

After summary of requirements I got the error 

---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot/main.py", line 78, in <module>
    project.start()
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot/helpers/Project.py", line 90, in start
    self.project_manager.get_project_description()
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot/helpers/agents/ProductOwner.py", line 65, in get_project_description
    save_progress(self.project.args['app_id'], self.project.current_step, {
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot/database/database.py", line 174, in save_progress
    app = get_app(app_id)
          ^^^^^^^^^^^^^^^
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot/database/database.py", line 192, in get_app
    app = App.get(App.id == app_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 6688, in get
    return sq.get()
           ^^^^^^^^
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 7136, in get
    return clone.execute(database)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 4485, in __getitem__
    self.fill_cache(item if item > 0 else 0)
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 4533, in fill_cache
    iterator.next()
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 4588, in next
    self.cursor_wrapper.iterate()
  File "/Users/michaeltrimmel/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 4508, in iterate
    result = self.process_row(row)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 7765, in process_row
    data = super(ModelObjectCursorWrapper, self).process_row(row)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 7731, in process_row
    result[attr] = converters[i](row[i])
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 5433, in python_value
    return self.rel_field.python_value(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/PycharmProjects/gpt-pilot/pilot-env/lib/python3.11/site-packages/peewee.py", line 5106, in python_value
    return uuid.UUID(value) if value is not None else None
           ^^^^^^^^^^^^^^^^
  File "/Users/mike/anaconda3/envs/llm/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
--------------------------------------------------
? We would appreciate if you let us store your initial app prompt. If you are OK with that, please just press ENTER

**Comment by senko** [comment]
Hey @miketrimmel thank you for reporting this! Did this happen when you started a new project, wanted to get a list of projects or tried to resume an existing project? Could you share the full command (with arguments) you used to start GPT Pilot?

**Comment by miketrimmel** [comment]
Hey @senko. It happened when I started a new project. After I checked the settings and posted it here I saw that postgres wasn´t commented in. Potentially this caused the problem. I also found out in the ,meanwhile that I didn´t exposed the port and for that I couldn´t connect to my docker instance.


I fixed exposure and commented in postgres, facing now another error. I think I have to clean up my workspace or run again init_db.py


The full command was 

python main.py user_id=mygithub email=mike@myemail.com

.env file is:

```
OPENAI_ENDPOINT=https://api.openai.com/v1/chat/completions
OPENAI_API_KEY=myopenaikey

AZURE_API_KEY=
AZURE_ENDPOINT=

OPENROUTER_API_KEY=

# In case of Azure/OpenRouter endpoint, change this to your deployed model name
MODEL_NAME=gpt-4-1106-preview
# MODEL_NAME=gpt-4
# MODEL_NAME=gpt-3.5-turbo-16k
MAX_TOKENS=8192

# Folders which shouldn't be tracked in workspace (useful to ignore folders created by compiler)
# IGNORE_FOLDERS=folder1,folder2

# Database
# DATABASE_TYPE=postgres

DB_NAME=gpt-pilot
DB_HOST=0.0.0.0
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=mypassword
```








```
2024-01-01 20:18:03 The files belonging to this database system will be owned by user "postgres".
2024-01-01 20:18:03 This user must also own the server process.
2024-01-01 20:18:03 
2024-01-01 20:18:03 The database cluster will be initialized with locale "en_US.utf8".
2024-01-01 20:18:03 The default database encoding has accordingly been set to "UTF8".
2024-01-01 20:18:03 The default text search configuration will be set to "english".
2024-01-01 20:18:03 
2024-01-01 20:18:03 Data page checksums are disabled.
2024-01-01 20:18:03 
2024-01-01 20:18:03 fixing permissions on existing directory /var/lib/postgresql/data ... ok
2024-01-01 20:18:03 creating subdirectories ... ok
2024-01-01 20:18:03 selecting dynamic shared memory implementation ... posix
2024-01-01 20:18:03 selecting default max_connections ... 100
2024-01-01 20:18:03 selecting default shared_buffers ... 128MB
2024-01-01 20:18:03 selecting default time zone ... Etc/UTC
2024-01-01 20:18:03 creating configuration files ... ok
2024-01-01 20:18:03 running bootstrap script ... ok
2024-01-01 20:18:03 performing post-bootstrap initialization ... ok
2024-01-01 20:18:04 syncing data to disk ... ok
2024-01-01 20:18:04 
2024-01-01 20:18:04 
2024-01-01 20:18:04 Success. You can now start the database server using:
2024-01-01 20:18:04 
2024-01-01 20:18:04     pg_ctl -D /var/lib/postgresql/data -l logfile start
2024-01-01 20:18:04 
2024-01-01 20:18:04 waiting for server to start....2024-01-01 19:18:04.031 UTC [48] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-01-01 20:18:04 2024-01-01 19:18:04.031 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-01-01 20:18:04 2024-01-01 19:18:04.033 UTC [51] LOG:  database system was shut down at 2024-01-01 19:18:03 UTC
2024-01-01 20:18:04 2024-01-01 19:18:04.035 UTC [48] LOG:  database system is ready to accept connections
2024-01-01 20:18:04  done
2024-01-01 20:18:04 server started
2024-01-01 20:18:04 
2024-01-01 20:18:04 /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
2024-01-01 20:18:04 
2024-01-01 20:18:04 waiting for server to shut down...2024-01-01 19:18:04.144 UTC [48] LOG:  received fast shutdown request
2024-01-01 20:18:04 .2024-01-01 19:18:04.146 UTC [48] LOG:  aborting any active transactions
2024-01-01 20:18:04 2024-01-01 19:18:04.147 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
2024-01-01 20:18:04 2024-01-01 19:18:04.147 UTC [49] LOG:  shutting down
2024-01-01 20:18:04 2024-01-01 19:18:04.148 UTC [49] LOG:  checkpoint starting: shutdown immediate
2024-01-01 20:18:04 2024-01-01 19:18:04.151 UTC [49] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.001 s, total=0.004 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/14EAA38, redo lsn=0/14EAA38
2024-01-01 20:18:04 initdb: warning: enabling "trust" authentication for local connections
2024-01-01 20:18:04 initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
2024-01-01 20:18:04 2024-01-01 19:18:04.259 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-01-01 20:18:04 2024-01-01 19:18:04.259 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-01-01 20:18:04 2024-01-01 19:18:04.259 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-01-01 20:18:04 2024-01-01 19:18:04.260 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-01-01 20:18:04 2024-01-01 19:18:04.262 UTC [62] LOG:  database system was shut down at 2024-01-01 19:18:04 UTC
2024-01-01 20:18:04 2024-01-01 19:18:04.264 UTC [1] LOG:  database system is ready to accept connections
2024-01-01 20:18:04 2024-01-01 19:18:04.153 UTC [48] LOG:  database system is shut down
2024-01-01 20:18:04  done
2024-01-01 20:18:04 server stopped
2024-01-01 20:18:04 
2024-01-01 20:18:04 PostgreSQL init process complete; ready for start up.
2024-01-01 20:18:04 
2024-01-01 20:23:04 2024-01-01 19:23:04.319 UTC [60] LOG:  checkpoint starting: time
2024-01-01 20:23:08 2024-01-01 19:23:08.525 UTC [60] LOG:  checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.196 s, sync=0.003 s, total=4.206 s; sync files=11, longest=0.003 s, average=0.001 s; distance=260 kB, estimate=260 kB; lsn=0/152BE58, redo lsn=0/152BE20
```
