### ISSUE TITLE
[Error] [Bug]: 

### ISSUE THREAD

**Issue by Real-Experienes** [Pythagora-io/gpt-pilot#495]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

Getting this error afterentering the description of the app and pressing enter. 
Can anyone advise??

`----------` GPT PILOT EXITING WITH ERROR ----------

Traceback (most recent call last):

File "c:\Users\luste\gpt-pilot\pilot\main.py", line 78, in <module> project.start()

File "c:\Users\luste\gpt-pilot\pilot\helpers\Project.py", line 90, in start self.project_manager.get_project_description()

File "c:\Users\luste\gpt-pilot\pilot\helpers\agents\ProductOwner.py", line 53, in get_project_description self.project.main_prompt = ask_for_main_app_definition(self.project) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\luste\gpt-pilot\pilot\prompts\prompts.py", line 40, in ask_for_main_app_definition description = styled_text( ^^^^^^^^^^^^

File "c:\Users\luste\gpt-pilot\pilot\utils\questionary.py", line 32, in styled_text response = print(question, type='user_input_request') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\luste\gpt-pilot\pilot\utils\custom_print.py", line 24, in print_to_external_process return ipc_client_instance.listen() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\luste\gpt-pilot\pilot\helpers\ipc.py", line 32, in listen message = json.loads(data) ^^^^^^^^^^^^^^^^

File "C:\Users\luste\AppData\Local\Programs\Python\Python312\Lib\json_init_.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\luste\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\luste\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) ^^^^^^^^^^^^^^^^^^^^^^

json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 30 (char 29)

**Comment by senko** [comment]
Could you tell us how long the prompt is (how many characters?), or if you're comfortable with it, share the prompt here so we can try?

**Comment by Real-Experienes** [comment]
Hey senko, thanks again for taking the time to reply/help. Even if we can't get it solved --I appreciate you man!!

The prompt is 56 lines | 294 words | 1715 characters.

**Comment by senko** [comment]
> Hey senko, thanks again for taking the time to reply/help. Even if we can't get it solved --I appreciate you man!!
> 
> The prompt is 56 lines | 294 words | 1715 characters.

Thanks! We just merged a fix. It'll be a few days before we have a new release with it, but if you're feeling adventurous, you can locate `gpt-pilot\pilot\helpers\ipc.py` file in your GPT Pilot installation folder, then find the line:

```python
data = self.client.recv(4096)
```

and change it to:

```python
data = self.client.recv(65536)
```

(that is, just change the number).

**Comment by Real-Experienes** [comment]
🙏 🤨 let the adventure begin ❣️
Thanks again!

**Comment by Real-Experienes** [comment]
Worked like a dream. 
Thanks again!

**Comment by Real-Experienes** [comment]
[SOLVED]
