### ISSUE TITLE
ValueError: Unsupported DATABASE_TYPE: postgres

### ISSUE THREAD

**Issue by ramkrishna757575** [Pythagora-io/gpt-pilot#50]
When setting this project up, and following the documentation under the `How to start using gpt-pilot?` section, the documentation at step number 8 mentions setting up the environment variable in the `.env` file.

Here it mentions the following:
```
to change from SQLite to PostgreSQL in your .env just set DATABASE_TYPE=postgres
```

But this results in an error:

```
Traceback (most recent call last):
  File "/home/ramkrishna/Documents/experiments/gpt-pilot/pilot/db_init.py", line 5, in <module>
    drop_tables()
  File "/home/ramkrishna/Documents/experiments/gpt-pilot/pilot/database/database.py", line 385, in drop_tables
    raise ValueError(f"Unsupported DATABASE_TYPE: {DATABASE_TYPE}")
ValueError: Unsupported DATABASE_TYPE: postgres
```

The error seems to be due to this check in `pilot/database/database.py:380`
```
            if DATABASE_TYPE == "postgresql":
                sql = f'DROP TABLE IF EXISTS "{table._meta.table_name}"'
            elif DATABASE_TYPE == "sqlite":
                sql = f'DROP TABLE IF EXISTS "{table._meta.table_name}"'
            else:
                raise ValueError(f"Unsupported DATABASE_TYPE: {DATABASE_TYPE}")
```

The correct check should be:

```
            if DATABASE_TYPE == "postgres":
                sql = f'DROP TABLE IF EXISTS "{table._meta.table_name}"'
            elif DATABASE_TYPE == "sqlite":
                sql = f'DROP TABLE IF EXISTS "{table._meta.table_name}"'
            else:
                raise ValueError(f"Unsupported DATABASE_TYPE: {DATABASE_TYPE}")
```

**Comment by ramkrishna757575** [comment]
Should I go ahead and create a PR for this fix?

**Comment by zvone187** [comment]
Yes, please do - great catch
