### ISSUE TITLE
Encountering error

### ISSUE THREAD

**Issue by steven-reyes** [Pythagora-io/gpt-pilot#516]
File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\main.py", line 79, in <module> project.start()

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\Project.py", line 141, in start self.developer.start_coding()

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 70, in start_coding self.implement_task(i, dev_task)

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 117, in implement_task result = self.execute_task(convo_dev_task, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 404, in execute_task result = self.step_command_run(convo, step, i, success_with_cli_response=need_to_see_output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 199, in step_command_run return run_command_until_success(convo, data['command'], ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\cli.py", line 479, in run_command_until_success cli_response, response, exit_code = execute_command(convo.agent.project, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\cli.py", line 305, in execute_command terminate_process(process.pid) # TODO: background_command - remove this is if we want to leave command running in background, look todo above ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\cli.py", line 127, in terminate_process term_proc_windows(pid)

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\cli.py", line 90, in term_proc_windows subprocess.run(["taskkill", "/F", "/T", "/PID", str(pid)])

File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run with Popen(*popenargs, **kwargs) as process: ^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in init self._execute_child(args, executable, preexec_fn, close_fds,

File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [WinError 2] The system cannot find the file specified

--------------------------------------------------

Traceback (most recent call last):

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\main.py", line 90, in

exit_gpt_pilot(project, ask_feedback)

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\utils\exit.py", line 97, in exit_gpt_pilot

terminate_running_processes()

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\cli.py", line 85, in terminate_running_processes

terminate_process(running_processes[command_id][1], command_id)

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\cli.py", line 127, in terminate_process

term_proc_windows(pid)

File "c:\Users\steve\OneDrive\Desktop\GPT Pilot Projects\gpt-pilot\pilot\helpers\cli.py", line 90, in term_proc_windows

subprocess.run(["taskkill", "/F", "/T", "/PID", str(pid)])

File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run

with Popen(*popenargs, **kwargs) as process:

^

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__

self._execute_child(args, executable, preexec_fn, close_fds,

File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child

hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

^^^^

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by techjeylabs** [comment]
closing this after inactivity and insufficient problem description
