### ISSUE TITLE
[Bug]: creating empty rails app make it crash while cd to location

### ISSUE THREAD

**Issue by psklodowski421** [Pythagora-io/gpt-pilot#536]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

What happens?
Gpt-pilot crashing while creating empty rails app

Way to reproduce:
Create new gpt-pilot app and set project description: Create empty rails app with hello world

`Dev step 2

--------- EXECUTE COMMAND ----------

Can I execute the command: `rails new hello_world --skip-test --skip-bundle` with 30000ms timeout?
yes

answer: yes
CLI OUTPUT: create app
...

DONE
Dev step 3

--------- EXECUTE COMMAND ----------

Can I execute the command: `cd hello_world` with 5000ms timeout?
yes

answer: yes
...

DONE
Dev step 4

---------- GPT PILOT EXITING WITH ERROR ----------

Traceback (most recent call last):

File "/Users/user/RubymineProjects/gpt-pilot/pilot/main.py", line 83, in <module> project.start()

File "/Users/user/RubymineProjects/gpt-pilot/pilot/helpers/Project.py", line 143, in start self.developer.start_coding()

File "/Users/user/RubymineProjects/gpt-pilot/pilot/helpers/agents/Developer.py", line 70, in start_coding self.implement_task(i, dev_task)

File "/Users/user/RubymineProjects/gpt-pilot/pilot/helpers/agents/Developer.py", line 117, in implement_task result = self.execute_task(convo_dev_task,

File "/Users/user/RubymineProjects/gpt-pilot/pilot/helpers/agents/Developer.py", line 409, in execute_task result = self.step_code_change(convo, task_description, step, i, test_after_code_changes)

File "/Users/user/RubymineProjects/gpt-pilot/pilot/helpers/agents/Developer.py", line 182, in step_code_change self.project.save_file(data)

File "/Users/user/RubymineProjects/gpt-pilot/pilot/helpers/Project.py", line 268, in save_file update_file(full_path, data['content'], project=self)

File "/Users/user/RubymineProjects/gpt-pilot/pilot/helpers/files.py", line 30, in update_file with open(path, file_mode, encoding=encoding) as file:

IsADirectoryError: [Errno 21] Is a directory: '/Users/user/RubymineProjects/gpt-pilot/workspace/hello_world/Gemfile/'

--------------------------------------------------`

**Comment by bc-rep-project** [comment]
This error occurs when the code attempts to open a file for writing, but the specified path is a directory instead of a file. In this case, the path is '/Users/user/RubymineProjects/gpt-pilot/workspace/hello_world/Gemfile/'.

To resolve this issue, you should check the path being passed to the open function and make sure it points to a valid file, not a directory. If the intention is to write to a file, ensure that the path includes the file name, not just the directory.

**Comment by techjeylabs** [comment]
does this issue persist ?
