### ISSUE TITLE
[Bug]:   GPT CoPilot hangs up.

### ISSUE THREAD

**Issue by jdcrunchman** [Pythagora-io/gpt-pilot#540]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

we came up with a situation where an Open AI error occurred,  then it just hangs up.    It then printed a stack trace on the code.
---------- GPT PILOT EXITING WITH ERROR ----------

Traceback (most recent call last):

File "/Volumes/T7/Programming/CoPilotGPT/gpt-pilot/pilot/main.py", line 79, in <module> project.start()

File "/Volumes/T7/Programming/CoPilotGPT/gpt-pilot/pilot/helpers/Project.py", line 141, in start self.developer.start_coding()

File "/Volumes/T7/Programming/CoPilotGPT/gpt-pilot/pilot/helpers/agents/Developer.py", line 70, in start_coding self.implement_task(i, dev_task)

File "/Volumes/T7/Programming/CoPilotGPT/gpt-pilot/pilot/helpers/agents/Developer.py", line 107, in implement_task response = convo_dev_task.send_message('development/parse_task.prompt', { ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/Volumes/T7/Programming/CoPilotGPT/gpt-pilot/pilot/helpers/AgentConvo.py", line 100, in send_message raise Exception("OpenAI API error happened.")

Exception: OpenAI API error happened.

--------------------------------------------------

Pilot didn't give me anyway to ask it to solve the error,  it just dumped the error on me.    I have no clue what to do,   this is definitely a show stopper.
I can go no further using this AI.

**Comment by jdcrunchman** [comment]
Is there any workaround that can help me get started where it left off?
or an "un-hang" command that can give me a way to send more prompts to Pilot?

**Comment by jdcrunchman** [comment]
Pilot says:   We would appreciate if you let us store your initial app prompt. If you are OK with that, please just press ENTER

But no prompt was given,  but I pressed "enter" anyway,  nothing happened.  Now it's just hung up.   Is there a way to back trace ?
