### ISSUE TITLE
[Bug]: Unable to resume development after closing GPT-pilot for any reason

### ISSUE THREAD

**Issue by dookiejones** [Pythagora-io/gpt-pilot#579]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

I completely removed and reinstalled GPT-pilot about 10 hours ago to ensure I had the latest updates and no conflicts. When development is suspended for any reason including extension crashes, or shutting down VS code, GPT-pilot is unable to resume development on the project. GPT-pilot exits with the following traceback.

```
Traceback (most recent call last):

File "c:\Users\Bots\pilot\gpt-pilot\pilot\main.py", line 97, in <module> started = project.start() ^^^^^^^^^^^^^^^

File "c:\Users\Bots\pilot\gpt-pilot\pilot\helpers\Project.py", line 166, in start self.developer.start_coding()

File "c:\Users\Bots\pilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 71, in start_coding self.implement_task(i, dev_task)

File "c:\Users\Bots\pilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 128, in implement_task result = self.execute_task(convo_dev_task, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\Bots\pilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 410, in execute_task result = self.step_human_intervention(convo, step) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\Bots\pilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 245, in step_human_intervention response['success'] = self.debugger.debug(convo, ^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\Users\Bots\pilot\gpt-pilot\pilot\helpers\Debugger.py", line 72, in debug logger.info('Thoughts: ' + llm_response['thoughts']) ~~~~~~~~~~~~^^^^^^^^^^^^

KeyError: 'thoughts' 
```

**Comment by dookiejones** [comment]
The issue seems to be corrected in the latest updates.
