### ISSUE TITLE
Very specific errors

### ISSUE THREAD

**Issue by Real-Experienes** [Pythagora-io/gpt-pilot#604]
### Version

Command-line (Python) version

### Operating System

Windows 11

### Your question

After constantly getting to 56% of the project complete, gtp-pilot exits with some very specific errors. Each time I completely delete all files and folders and start over from scratch---I get a new error or set of errors. Also, even though I can find my flutter, android studio and cmd tools when I use cmd to check for them, gpt-pilot in the Command-line version cannot. Can you guys help me past these two issues? I have checked the indicated lines but there is nothing to be corrected on them as they are just code. 
Please advise.
Thanks in advance for ANY advice and guidance!

---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "C:\development\gpt-pilot\pilot\main.py", line 97, in <module>
    started = project.start()
              ^^^^^^^^^^^^^^^
  File "C:\development\gpt-pilot\pilot\helpers\Project.py", line 191, in start
    self.developer.start_coding()
  File "C:\development\gpt-pilot\pilot\helpers\agents\Developer.py", line 84, in start_coding
    self.implement_task(i, dev_task)
  File "C:\development\gpt-pilot\pilot\helpers\agents\Developer.py", line 121, in implement_task
    instructions = convo_dev_task.send_message('development/task/breakdown.prompt', {
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\development\gpt-pilot\pilot\helpers\AgentConvo.py", line 74, in send_message
    save_development_step(self.agent.project, prompt_path, prompt_data, self.messages, response)
  File "C:\development\gpt-pilot\pilot\database\database.py", line 301, in save_development_step
    project.save_files_snapshot(development_step.id)
  File "C:\development\gpt-pilot\pilot\helpers\Project.py", line 460, in save_files_snapshot
    files = get_directory_contents(self.root_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\development\gpt-pilot\pilot\helpers\files.py", line 117, in get_directory_contents
    if matcher.ignore(full_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\development\gpt-pilot\pilot\utils\ignore.py", line 53, in ignore
    if self.ignore_binaries and self.is_binary(path):
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\development\gpt-pilot\pilot\utils\ignore.py", line 94, in is_binary
    open(path, "r", encoding="utf-8").read(128*1024)
PermissionError: [Errno 13] Permission denied
--------------------------------------------------

**Comment by Myster-Macintosh** [comment]
same question

**Comment by techjeylabs** [comment]
those this issue still persists ?

**Comment by Real-Experienes** [comment]
I am restarting the prompts today as I just upgraded to a 32GB workstation
and I will be installing 64GB later this week.

I just set up a new env so I will let you know how it goes.

**Comment by techjeylabs** [comment]
keep it goin, i am here to assist :)!
