### ISSUE TITLE
[Bug]: Crash when you tell it to 

### ISSUE THREAD

**Issue by stevebrainng** [Pythagora-io/gpt-pilot#627]
### Version

Command-line (Python) version

### Operating System

Windows 11

### What happened?

When I tell Gpt-pilot not to debug any errors or to just continue development steps Instead of debugging, GPT-pilot exit with the following errors.

---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "C:\src\development\Python\gpt-pilot\pilot\main.py", line 97, in <module>
    started = project.start()
              ^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\Project.py", line 192, in start
    self.developer.start_coding()
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\agents\Developer.py", line 84, in start_coding
    self.implement_task(i, dev_task)
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\agents\Developer.py", line 195, in implement_task
    result = self.execute_task(convo_dev_task,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\agents\Developer.py", line 497, in execute_task
    result = self.step_command_run(convo, task_steps, i, success_with_cli_response=need_to_see_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\agents\Developer.py", line 268, in step_command_run
    return run_command_until_success(convo, data['command'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\cli.py", line 499, in run_command_until_success
    success = convo.agent.debugger.debug(convo, {
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\Debugger.py", line 86, in debug
    result = self.agent.project.developer.execute_task(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\agents\Developer.py", line 497, in execute_task
    result = self.step_command_run(convo, task_steps, i, success_with_cli_response=need_to_see_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\agents\Developer.py", line 268, in step_command_run
    return run_command_until_success(convo, data['command'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\cli.py", line 499, in run_command_until_success
    success = convo.agent.debugger.debug(convo, {
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\development\Python\gpt-pilot\pilot\helpers\Debugger.py", line 97, in debug
    if 'step_index' in result:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
--------------------------------------------------

**Comment by techjeylabs** [comment]
hey there it seems like a duplicate: https://github.com/Pythagora-io/gpt-pilot/issues/387


just follow these steps, it should work afterwards. From what it looks like your gpt-pilot is not ready.

> When setting up GPT-Pilot VSCode extension in windows, one of the steps is to create the Python virtual environment (venv).
> 
> This can fail (for as of yet unknown reason), and this is what the users see:
> 
> ![image](https://private-user-images.githubusercontent.com/3362/292340111-7dbd5926-c94b-404c-b1eb-eaaef606c701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTU2OTksIm5iZiI6MTcxMzc5NTM5OSwicGF0aCI6Ii8zMzYyLzI5MjM0MDExMS03ZGJkNTkyNi1jOTRiLTQwNGMtYjFlYi1lYWFlZjYwNmM3MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMTQxNjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGIwMzJhNzliMmY4M2Y2NzBmYjM5ZDdmMGYwMzU4YzczYWM4YjE2OGYxZWVjN2RhMGU0ODA1MjE2NWZkNmE4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FyoPXLBbsRUaXFv7GY7IDS2KNtXWZL0ItKEaNyG9WUg)
> 
> Temporary workaround:
> 
> 1. open command line in the `gpt-pilot` sub-directory of the folder which you selected for the installation of GPT Pilot (there should be `requirements.txt` file already there)
> 2. create the virtual environment with `python -m venv pilot-env`
> 3. activate the environment with `pilot-env\Scripts\activate`
> 4. install packages with `pip install -r requirements.txt`
> 5. go to the `pilot` subdirectory (not `pilot-env`, just `pilot`). If there is `gpt-pilot` file in that subdirectory delete it (that is sqlite database) and then run `python db_init.py` to initialize new database
> 
> After doing the above steps, the VSCode extension should start working.
