### ISSUE TITLE
[Bug]:  The app crashed.

### ISSUE THREAD

**Issue by giorgosn** [Pythagora-io/gpt-pilot#709]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

I was in the task 1 and I got this error

---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\main.py", line 101, in <module>
    started = project.start()

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\Project.py", line 225, in start
    self.developer.start_coding('app')

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 91, in start_coding
    self.implement_task(i, task_source, dev_task)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 215, in implement_task
    result = self.execute_task(convo_dev_task,

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 597, in execute_task
    return self.task_postprocessing(convo, development_task, continue_development, result, function_uuid)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 412, in task_postprocessing
    return self.continue_development(convo, last_branch_name, continue_description, development_task)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 672, in continue_development
    user_feedback = self.bug_report_generator(user_feedback, user_description)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\agents\Developer.py", line 767, in bug_report_generator
    user_feedback = bug_report_summary_convo.send_message('development/bug_report_summary.prompt', {

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\AgentConvo.py", line 104, in send_message
    self.log_message(message_content)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\helpers\AgentConvo.py", line 244, in log_message
    print(f"\n{content}\n", type='local')

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\utils\custom_print.py", line 17, in print_to_external_process
    local_print(*args, **kwargs)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot\utils\custom_print.py", line 38, in local_print
    built_in_print(message, **kwargs)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot-env\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot-env\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot-env\lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "c:\Users\Npizza\Desktop\gpt pilot projects\gpt-pilot\pilot-env\lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])

  File "C:\Users\Npizza\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\u2a2f' in position 116: character maps to <undefined>

If you know what is going on please help me

**Comment by jwuliger** [comment]
Hello, great project you have going! This is the first time I tried the extension. I was able to get as far as instructing it what to build, then when it tries to begin I get the same error above. I am on the very latest version. It just updated itself.
