### ISSUE TITLE
[Bug]: gpt-pilot saved all content in package.json

### ISSUE THREAD

**Issue by lebe-dev** [Pythagora-io/gpt-pilot#721]
### Version

VisualStudio Code extension

### Operating System

Linux (other)

### What happened?

I've tried to create a demo base64 encoder / decoder app.

My prompt was:

```
Create an web app for encode / decode base64. Main page should have title and H1 heading "BASE64 :: Encoder / Decoder" User should have single multiline input for text and two buttons: encode and decode. Input should have placeholder "Enter the text to encode / decode" After user encode or decode text app should provide "copy to clipboard" button. Use #04ff00 as a primary color button. Use tailwind css and daisyui frameworks, load them from CDN. No backend should used.
```

GP created `package.json` with html, js and project configuration: [package.json](https://github.com/Pythagora-io/gpt-pilot/files/14593327/package.json)

Then it threw an error:

```
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):

  File "/home/aaa/sync/pro/rnd/rnd-gpt-pilot/gpt-pilot/pilot/main.py", line 101, in <module>
    started = project.start()
              ^^^^^^^^^^^^^^^

  File "/home/aaa/sync/pro/rnd/rnd-gpt-pilot/gpt-pilot/pilot/helpers/Project.py", line 225, in start
    self.developer.start_coding('app')

  File "/home/aaa/sync/pro/rnd/rnd-gpt-pilot/gpt-pilot/pilot/helpers/agents/Developer.py", line 91, in start_coding
    self.implement_task(i, task_source, dev_task)

  File "/home/aaa/sync/pro/rnd/rnd-gpt-pilot/gpt-pilot/pilot/helpers/agents/Developer.py", line 215, in implement_task
    result = self.execute_task(convo_dev_task,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/aaa/sync/pro/rnd/rnd-gpt-pilot/gpt-pilot/pilot/helpers/agents/Developer.py", line 539, in execute_task
    result = self.step_command_run(convo, task_steps, i, success_with_cli_response=need_to_see_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/aaa/sync/pro/rnd/rnd-gpt-pilot/gpt-pilot/pilot/helpers/agents/Developer.py", line 280, in step_command_run
    return run_command_until_success(convo, data['command'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/aaa/sync/pro/rnd/rnd-gpt-pilot/gpt-pilot/pilot/helpers/cli.py", line 499, in run_command_until_success
    success = convo.agent.debugger.debug(convo, {
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/aaa/sync/pro/rnd/rnd-gpt-pilot/gpt-pilot/pilot/helpers/Debugger.py", line 101, in debug
    if 'step_index' in result:
       ^^^^^^^^^^^^^^^^^^^^^^

TypeError: argument of type 'NoneType' is not iterable

--------------------------------------------------
```

**Comment by techjeylabs** [comment]
i am not to sure if this is reproduceable, as i have tested your original prompt myself. Pythagora runs thrue and sets up everything as expected.
