### ISSUE TITLE
[Bug]: cannot import name 'ApiError' when click "Create New App"

### ISSUE THREAD

**Issue by TheCompAce** [Pythagora-io/gpt-pilot#726]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

When trying to use "Create new App" I get ..
`Traceback (most recent call last):
  File "t:\Tensorflow\gpt-pilot\pilot\main.py", line 18, in <module>
    from helpers.Project import Project
  File "t:\Tensorflow\gpt-pilot\pilot\helpers\Project.py", line 15, in <module>
    from prompts.prompts import ask_user
  File "t:\Tensorflow\gpt-pilot\pilot\prompts\prompts.py", line 5, in <module>
    from utils.llm_connection import create_gpt_chat_completion
  File "t:\Tensorflow\gpt-pilot\pilot\utils\llm_connection.py", line 16, in <module>
    from helpers.exceptions import TokenLimitError, ApiKeyNotDefinedError, ApiError
ImportError: cannot import name 'ApiError' from 'helpers.exceptions' (t:\Tensorflow\gpt-pilot\pilot\helpers\exceptions\__init__.py)
`

**Comment by raptorfrog** [comment]
I am seeing this same error on one of my development laptops with Windows 11, but not the other.

**Comment by raptorfrog** [comment]
> I am seeing this same error on one of my development laptops with Windows 11, but not the other.

I was able to work around this issue by uninstalling visual studio code, and deleting the Code directory under Appdata, this got me back to where I could do a "real" fresh install and then everything works fine. I suspect it's somehow related to the fact I had GPT Pilot installed before installing the updated extension, but can't say for sure. Of note, the system that it was working fine on was a completely new laptop where it had a fresh install of Code and the required extensions.

**Comment by lyndonb1** [comment]
Reinstalling vs code is pretty radical if you use it for a lot of things and have some settings you want to keep. I was able to fix this by deleting the gpt pilot directory and reinstalling gpt-pilot.
