### ISSUE TITLE
[Bug]: GPT Pilot Crash when during generating code

### ISSUE THREAD

**Issue by liratanak** [Pythagora-io/gpt-pilot#750]
### Version

VisualStudio Code extension

### Operating System

Ubuntu Linux

### What happened?

When it's generate module in auth wit jwt token with nestjs it crash

```
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot/main.py", line 112, in <module>
    started = project.start()

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot/helpers/Project.py", line 225, in start
    self.developer.start_coding('app')

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot/helpers/agents/Developer.py", line 91, in start_coding
    self.implement_task(i, task_source, dev_task)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot/helpers/agents/Developer.py", line 215, in implement_task
    result = self.execute_task(convo_dev_task,

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot/helpers/agents/Developer.py", line 545, in execute_task
    result = self.step_save_file(convo, step, i, test_after_code_changes)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot/helpers/agents/Developer.py", line 268, in step_save_file
    code_monkey.implement_code_changes(convo, data)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot/helpers/agents/CodeMonkey.py", line 130, in implement_code_changes
    self.project.save_file({

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot/helpers/Project.py", line 412, in save_file
    .execute())

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 1971, in inner
    return method(self, database, *args, **kwargs)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 2042, in execute
    return self._execute(database)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 2847, in _execute
    return super(Insert, self)._execute(database)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 2560, in _execute
    cursor = database.execute(self)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 3258, in execute
    sql, params = ctx.sql(query).query()

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 628, in sql
    return obj.__sql__(self)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 2836, in __sql__
    update = self._on_conflict.get_conflict_update(ctx, self)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 1925, in get_conflict_update
    return ctx.state.conflict_update(self, query)

  File "/home/liratanak/Lab/GPT-Pilot/gpt-pilot/pilot-env/lib/python3.10/site-packages/peewee.py", line 3854, in conflict_update
    raise ValueError('SQLite does not support specifying which values '

ValueError: SQLite does not support specifying which values to preserve or update.

--------------------------------------------------

```

**Comment by senko** [comment]
This error looks like GPT Pilot was running twice and using the same database (from the same installation folder), which SQLite doesn't support, so it resulted in update conflict.

**Comment by bum2free** [comment]
then how to recover from this error? re-run python main.py app_id=... seems not work

**Comment by techjeylabs** [comment]
i assume you have to go 1 step back in your project. and start over that step again.
