### ISSUE TITLE
[Bug]: \u0000 cannot be converted to text

### ISSUE THREAD

**Issue by maci0** [Pythagora-io/gpt-pilot#753]
### Version

Command-line (Python) version

### Operating System

Ubuntu Linux

### What happened?

I am using gpt pilot to help me write an assembler. somewhere it seems some jsonb is handed over but peewee expects regular json.

```
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3251, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.UntranslatableCharacter: unsupported Unicode escape sequence
LINE 1: ...', 'development/parse_task.prompt', 1, NULL, CAST('[{"role":...
                                                             ^
DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: ...*src/output.bin** (1 lines of code):\n```\n\u0000...


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/pilot/main.py", line 112, in <module>
    started = project.start()
              ^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/Project.py", line 225, in start
    self.developer.start_coding('app')
  File "/usr/src/app/pilot/helpers/agents/Developer.py", line 91, in start_coding
    self.implement_task(i, task_source, dev_task)
  File "/usr/src/app/pilot/helpers/agents/Developer.py", line 165, in implement_task
    response = convo_dev_task.send_message('development/parse_task.prompt', {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/AgentConvo.py", line 76, in send_message
    save_development_step(self.agent.project, prompt_path, prompt_data, self.messages, response)
  File "/usr/src/app/pilot/database/database.py", line 358, in save_development_step
    development_step = hash_and_save_step(DevelopmentSteps, project.args['app_id'], unique_data, data_fields,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/database/database.py", line 331, in hash_and_save_step
    .execute())
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 1971, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2042, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2847, in _execute
    return super(Insert, self)._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2558, in _execute
    cursor = self.execute_returning(database)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 2565, in execute_returning
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3259, in execute
    return self.execute_sql(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3249, in execute_sql
    with __exception_wrapper__:
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3019, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3251, in execute_sql
    cursor.execute(sql, params or ())
peewee.DataError: unsupported Unicode escape sequence
LINE 1: ...', 'development/parse_task.prompt', 1, NULL, CAST('[{"role":...
                                                             ^
DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: ...*src/output.bin** (1 lines of code):\n```\n\u0000...

--------------------------------------------------
```

here is what the output from the container looks like

```
teps.\n\nExamples:\n------------------------example_1---------------------------\n```\n{\n  \"tasks\": [\n    {\n      \"type\": \"save_file\",\n      \"save_file\": {\n        \"name\": \"server.js\",\n        \"path\": \"/server.js\",\n        \"code_change_description\": \"\",\n      },\n    },\n    {\n      \"type\": \"command\",\n      \"command\": {\n        \"command\": \"ls\",\n        \"timeout\": \"5000\",\n        \"success_message\": \"README.md\",\n        \"command_id\": \"check_existence_of_readme_file\"\n      }\n    }\n  ]\n}\n```\n------------------------end_of_example_1---------------------------"}]' AS jsonb), CAST('{"text": "{\n    \"tasks\": [\n        {\n            \"type\": \"save_file\",\n            \"save_file\": {\n                \"name\": \"assembler_cli.py\",\n                \"path\": \"/src/assembler_cli.py\",\n                \"code_change_description\": \"\"\n            }\n        },\n        {\n            \"type\": \"save_file\",\n            \"save_file\": {\n                \"name\": \"parser.py\",\n                \"path\": \"/src/parser.py\",\n                \"code_change_description\": \"\"\n            }\n        },\n        {\n            \"type\": \"save_file\",\n            \"save_file\": {\n                \"name\": \"isa.py\",\n                \"path\": \"/src/isa.py\",\n                \"code_change_description\": \"\"\n            }\n        },\n        {\n            \"type\": \"save_file\",\n            \"save_file\": {\n                \"name\": \"encoder.py\",\n                \"path\": \"/src/encoder.py\",\n                \"code_change_description\": \"\"\n            }\n        },\n        {\n            \"type\": \"save_file\",\n            \"save_file\": {\n                \"name\": \"symbol_table.py\",\n                \"path\": \"/src/symbol_table.py\",\n                \"code_change_description\": \"\"\n            }\n        },\n        {\n            \"type\": \"save_file\",\n            \"save_file\": {\n                \"name\": \"file_output.py\",\n                \"path\": \"/src/file_output.py\",\n                \"code_change_description\": \"\"\n            }\n        },\n        {\n            \"type\": \"command\",\n            \"command\": {\n                \"command\": \"python -m pip install pytest\",\n                \"timeout\": 60000,\n                \"success_message\": \"Successfully installed pytest\"\n            }\n        }\n    ]\n}"}' AS jsonb), CAST('{"os": "Linux", "instructions_prefix": "To implement task #8, we", "instructions_postfix": "specified in the task description.", "function_call_message": {"role": "user", "content": "**IMPORTANT**\nYou must respond with ONLY the JSON object, with NO additional text or explanation.\n\nHere is the schema for the expected JSON object:\n```json\n{\n    \"tasks\": {\n        \"type\": \"array\",\n        \"description\": \"List of smaller development steps.\",\n        \"items\": {\n            \"oneOf\": [\n                {\n                    \"type\": \"object\",\n                    \"properties\": {\n                        \"type\": {\n                            \"const\": \"command\",\n                            \"description\": \"Type of the development step that needs to be done to complete the entire task.\"\n                        },\n                        \"command\": {\n                            \"type\": \"object\",\n                            \"description\": \"Command that needs to be run to complete the current task. This should be used only if the task is of a type \\\"command\\\".\",\n                            \"properties\": {\n                                \"command\": {\n                                    \"type\": \"string\",\n                                    \"description\": \"A single command that needs to be executed.\"\n                                },\n                                \"timeout\": {\n                                    \"type\": \"number\",\n                                    \"description\": \"Timeout in milliseconds that represent the approximate time this command takes to finish. If you need to run a command that doesnt''t finish by itself (eg. a command to run an app), set the timeout to to a value long enough to determine that it has started successfully and provide a command_id. If you need to create a directory that doesn''t exist and is not the root project directory, always create it by running a command `mkdir`\"\n                                },\n                                \"success_message\": {\n
\"type\": \"string\",\n                                    \"description\": \"A message to look for in the output of the command to determine if successful or not.\"\n
      },\n                                \"command_id\": {\n                                    \"type\": \"string\",\n                                    \"description\": \"If the process needs to continue running after the command is executed provide a unique command identifier which you can use to kill the process later.\"\n                                }\n
       },\n                            \"required\": [\n                                \"command\",\n                                \"timeout\"\n                            ]\n
         }\n                    },\n                    \"required\": [\n                        \"type\",\n                        \"command\"\n                    ]\n                },\n                {\n                    \"type\": \"object\",\n                    \"properties\": {\n                        \"type\": {\n                            \"const\": \"save_file\",\n                            \"description\": \"Type of the development step that needs to be done to complete the entire task.\"\n                        },\n                        \"save_file\": {\n                            \"type\": \"object\",\n                            \"description\": \"A file that should be created or updated.\",\n                            \"properties\": {\n                                \"name\": {\n                                    \"type\": \"string\",\n                                    \"description\": \"Name of the file that will be created (if it doesn''t exist) or updated (if it already exists).\"\n                                },\n                                \"path\": {\n                                    \"type\": \"string\",\n                                    \"description\": \"Full path of the file with the file name.\"\n                                },\n                                \"code_change_description\": {\n                                    \"type\": \"string\",\n                                    \"description\": \"Empty string\"\n                                }\n
                   },\n                            \"required\": [\n                                \"name\",\n                                \"path\",\n                                \"code_change_description\"\n                            ]\n                        }\n                    },\n                    \"required\": [\n                        \"type\",\n
       \"save_file\"\n                    ]\n                },\n                {\n                    \"type\": \"object\",\n                    \"properties\": {\n                        \"type\": {\n                            \"const\": \"human_intervention\",\n                            \"description\": \"Development step that will be executed by a human. You should avoid using this step if possible, task does NOT need to have \\\"human_intervention\\\" step.\"\n                        },\n                        \"human_intervention_description\": {\n
              \"type\": \"string\",\n                            \"description\": \"Very clear description of step where human intervention is needed.\"\n                        }\n
        },\n                    \"required\": [\n                        \"type\",\n                        \"human_intervention_description\"\n                    ]\n                }\n            ]\n        }\n    }\n}\n```\n\n"}}' AS jsonb), 115, 'coding') RETURNING "development_steps"."id"
```

**Comment by maci0** [comment]
gpt itself suggests this:

```
def sanitize_data(data):
    """
    Sanitize data by removing or replacing the '\u0000' character.
    """
    if isinstance(data, str):
        return data.replace('\u0000', '')  # Replace with '' or other suitable character
    elif isinstance(data, dict):
        return {key: sanitize_data(value) for key, value in data.items()}
    elif isinstance(data, list):
        return [sanitize_data(element) for element in data]
    else:
        return data

def hash_and_save_step(Model, app_id, unique_data_fields, data_fields, message):
    # Sanitize input data fields
    unique_data_fields = sanitize_data(unique_data_fields)
    data_fields = sanitize_data(data_fields)

    for field, value in data_fields.items():
        unique_data_fields[field] = value

    try:
        inserted_id = (Model
                       .insert(**unique_data_fields)
                       .execute())

        record = Model.get_by_id(inserted_id)
        # Sanitize data retrieved from the database, if necessary
        # record = sanitize_data(record)
        logger.debug(color_yellow(f"{message} with id {record.id}"))
    except IntegrityError:
        logger.warn(f"A record with data {unique_data_fields} already exists for {Model.__name__}.")
        return None
    return record
```

seems to get me past the issue

**Comment by senko** [comment]
The issue here is that the `*.bin` file is getting stored in the database. While your change may work around that, it's also going to be sent (unneccessarily) to the LLM, making everything slower, wasting tokens and money.

The ideal solution is to add these files to `IGNORE_PATHS` in the `.env`, so that GPT Pilot and the LLM never consider them.
