### ISSUE TITLE
[Bug]: ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by EddyLL06** [Pythagora-io/gpt-pilot#783]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

I installed Pythagora from the VS Code Extensions and after installing and registering, I clicked on "Create New App", and this error showed up:

Traceback (most recent call last):
  File "/Users/eddyliulin/Desktop/Programming/gpt-pilot/pilot/main.py", line 29, in <module>
    from helpers.Project import Project
  File "/Users/eddyliulin/Desktop/Programming/gpt-pilot/pilot/helpers/Project.py", line 15, in <module>
    from prompts.prompts import ask_user
  File "/Users/eddyliulin/Desktop/Programming/gpt-pilot/pilot/prompts/prompts.py", line 5, in <module>
    from utils.llm_connection import create_gpt_chat_completion
  File "/Users/eddyliulin/Desktop/Programming/gpt-pilot/pilot/utils/llm_connection.py", line 23, in <module>
    tokenizer = tiktoken.get_encoding("cl100k_base")
  File "/Users/eddyliulin/Desktop/Programming/gpt-pilot/pilot-env/lib/python3.9/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
  File "/Users/eddyliulin/Desktop/Programming/gpt-pilot/pilot-env/lib/python3.9/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/Users/eddyliulin/Desktop/Programming/gpt-pilot/pilot-env/lib/python3.9/site-packages/tiktoken/load.py", line 124, in load_tiktoken_bpe
    return {
  File "/Users/eddyliulin/Desktop/Programming/gpt-pilot/pilot-env/lib/python3.9/site-packages/tiktoken/load.py", line 126, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
ValueError: not enough values to unpack (expected 2, got 1)

I haven't do anything yet. I opened Pythagora in a empty project folder.

**Comment by liujb** [comment]
Same problem.
