### ISSUE TITLE
[Howto]: Start Pythagora, Mac, Apple silicon

### ISSUE THREAD

**Issue by liujb** [Pythagora-io/gpt-pilot#793]
### Version

VisualStudio Code extension

### Operating System

MacOS

### Your question

Start Pythagora on visual studio code，output this infomation, What can I do.

``` text
Traceback (most recent call last):
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot/main.py", line 29, in <module>
    from helpers.Project import Project
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot/helpers/Project.py", line 15, in <module>
    from prompts.prompts import ask_user
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot/prompts/prompts.py", line 5, in <module>
    from utils.llm_connection import create_gpt_chat_completion
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot/utils/llm_connection.py", line 23, in <module>
    tokenizer = tiktoken.get_encoding("cl100k_base")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken/load.py", line 124, in load_tiktoken_bpe
    return {
          ^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken/load.py", line 126, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
        ^^^^^^^
^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by senko** [comment]
Please do the following in terminal (in vscode or regular terminal) and paste the output here:

```
cd /Users/liujiangbei/Workspace/Pythagora/gpt-pilot/  # this places you in the gpt-pilot dir

source pilot-env/bin/activate  # this activates the Python environment used by gpt pilot

pip freeze | grep tiktoken  # this checks version of tiktoken (library that threw an error there)

python -c 'import tiktoken; print(tiktoken.get_encoding("cl100k_base"))'  # this checks that tiktoken library works

**Comment by liujb** [comment]
> 请在终端（在 vscode 或常规终端）中执行以下操作并将输出粘贴到此处：
> 
> ```
> cd /Users/liujiangbei/Workspace/Pythagora/gpt-pilot/  # this places you in the gpt-pilot dir
> 
> source pilot-env/bin/activate  # this activates the Python environment used by gpt pilot
> 
> pip freeze | grep tiktoken  # this checks version of tiktoken (library that threw an error there)
> 
> python -c 'import tiktoken; print(tiktoken.get_encoding("cl100k_base"))'  # this checks that tiktoken library works
> ```

pip freeze | grep tiktoken # print `tiktoken==0.5.2`

python -c 'import tiktoken; print(tiktoken.get_encoding("cl100k_base"))' # No response, and when `ctrl + c `, error

```
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken/load.py", line 123, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken/load.py", line 50, in read_file_cached
    contents = read_file(blobpath)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/tiktoken/load.py", line 24, in read_file
    resp = requests.get(blobpath)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/Workspace/Pythagora/gpt-pilot/pilot-env/lib/python3.11/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/.pyenv/versions/3.11.6/lib/python3.11/http/client.py", line 466, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/.pyenv/versions/3.11.6/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/.pyenv/versions/3.11.6/lib/python3.11/ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiangbei/.pyenv/versions/3.11.6/lib/python3.11/ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by liujb** [comment]
Upgrade GPT-Pilot, problem solved
