### ISSUE TITLE
[Bug]: Tokens rate limit has exceeded using anthropic/claude-3-sonnet-20240229

### ISSUE THREAD

**Issue by ngupta181** [Pythagora-io/gpt-pilot#855]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

Updating existing file \server.js:
Traceback (most recent call last):

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot\utils\llm_connection.py", line 149, in create_gpt_chat_completion
    response = stream_anthropic(messages, function_call_message, gpt_data, model_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot\utils\llm_connection.py", line 640, in stream_anthropic
    with client.messages.stream(

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot-env\Lib\site-packages\anthropic\lib\streaming\_messages.py", line 196, in __enter__
    self.__stream = self.__api_request()
                    ^^^^^^^^^^^^^^^^^^^^

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot-env\Lib\site-packages\anthropic\_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot-env\Lib\site-packages\anthropic\_base_client.py", line 897, in request
    return self._request(
           ^^^^^^^^^^^^^^

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot-env\Lib\site-packages\anthropic\_base_client.py", line 973, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot-env\Lib\site-packages\anthropic\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot-env\Lib\site-packages\anthropic\_base_client.py", line 973, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot-env\Lib\site-packages\anthropic\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^

  File "c:\Users\ngupta\Desktop\GPT\gpt-pilot\pilot-env\Lib\site-packages\anthropic\_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None

anthropic.RateLimitError: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': 'Number of request tokens has exceeded your rate limit (https://docs.anthropic.com/claude/reference/rate-limits). Please reduce the the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase.'}}

The request to OPENAI API failed with error: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': 'Number of request tokens has exceeded your rate limit (https://docs.anthropic.com/claude/reference/rate-limits). Please reduce the the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase.'}}. Please try again later.

**Comment by techjeylabs** [comment]
since you are getting rate limited its not exactly a GPT-Pilot issue, therefore i am gonna close this issue
