### ISSUE TITLE
[Bug]: errors pop up and it is impossible to continue the process when you start with the current step

### ISSUE THREAD

**Issue by gkostyukov** [Pythagora-io/gpt-pilot#898]
### Version

Command-line (Python) version

### Operating System

Windows 10

### What happened?

---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/usr/src/app/pilot/main.py", line 126, in <module>
    started = project.start()
              ^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/Project.py", line 229, in start
    self.developer.start_coding('app')
  File "/usr/src/app/pilot/helpers/agents/Developer.py", line 109, in start_coding
    task_executed = self.implement_task(i, task_source, dev_task)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/agents/Developer.py", line 253, in implement_task
    result = self.execute_task(convo_dev_task,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/agents/Developer.py", line 644, in execute_task
    result = self.step_command_run(convo, task_steps, i, success_with_cli_response=need_to_see_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/agents/Developer.py", line 379, in step_command_run
    return run_command_until_success(convo, data['command'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/cli.py", line 506, in run_command_until_success
    success = convo.agent.debugger.debug(convo, {
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/pilot/helpers/Debugger.py", line 101, in debug
    if 'step_index' in result:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by techjeylabs** [comment]
hey there, when does this happen ?
