### ISSUE TITLE
[Please i'm stucked at the Tech Lead Agent try to create a development ]: 

### ISSUE THREAD

**Issue by Brownie-08** [Pythagora-io/gpt-pilot#922]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### Your question

I created an app and after i got to the Tech Lead Agent he was about to create an  action plan  for development and i encounter this issue..  is an Error "---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):

  File "c:\Users\User\Desktop\ai projects\gpt-pilot\pilot\main.py", line 126, in <module>
    started = project.start()
              ^^^^^^^^^^^^^^^

  File "c:\Users\User\Desktop\ai projects\gpt-pilot\pilot\helpers\Project.py", line 217, in start
    self.tech_lead.create_development_plan()

  File "c:\Users\User\Desktop\ai projects\gpt-pilot\pilot\helpers\agents\TechLead.py", line 57, in create_development_plan
    "is_complex_app": self.project.is_complex_app,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'Project' object has no attribute 'is_complex_app'

--------------------------------------------------"

please i do need your help to proceed.. Am stucked at this point

**Comment by techjeylabs** [comment]
hey there, what model are you using? Are you using the Pythagora subscription or openai ?

**Comment by Peterbrown242** [comment]
I’m using both I have the open ai secret key and I have the Pythagora subscription with a 100,000 token.. please advice on what to do..

**Comment by Peterbrown242** [comment]
No I’m using gpt4 turbo

**Comment by Peterbrown242** [comment]
Is there any solution?
